---
- name: Configure Flyway
  become: true
  template:
    src=conf/flyway/flyway.conf
    dest=/opt/openolympus/flyway/flyway-3.2.1/conf/flyway.conf
    owner=openolympus
    group=openolympus
    force=true
    mode=0644
  tags:
    - configureDatabase

- name: Copy Flyway migrations
  become: true
  copy:
    src=conf/schemaMigrations
    dest=/opt/openolympus/flyway/flyway-3.2.1/sql/
    owner=openolympus
    group=openolympus
    force=true
    mode=0644
  tags:
    - configureDatabase