---
- name: Restart openolympus web service
  become: true
  service: name=openolympus_web state=restarted
- name: Start nginx
  become: true
  service: name=nginx state=started
- name: Reload nginx
  become: true
  service: name=nginx state=reloaded
- name: Clear nginx cache
  become: true
  file: path={{ nginx.cache_path }} recurse=yes state=absent
  file: path={{ nginx.cache_path }} mode=0664 owner=www-data group=www-data state=directory