---
- name: Download JPPF server
  become: true
  become_user: openolympus
  get_url:
    url=http://downloads.sourceforge.net/project/jppf-project/jppf-project/jppf%20{{ versions.jppf }}/JPPF-{{ versions.jppf }}-driver.zip
    dest=/opt/openolympus/tmp/jppfServer.zip
  tags:
    - installJppf

- name: Create JPPF server directory
  become: true
  file:
    state=directory
    path=/opt/openolympus/jppfServer/
    mode="u=rwx"
    owner=openolympus
    group=openolympus
  tags:
    - installJppf

- name: Extract JPPF server
  become: true
  unarchive:
    src=/opt/openolympus/tmp/jppfServer.zip
    dest=/opt/openolympus/jppfServer/
    owner=openolympus
    group=openolympus
    copy=no
  tags:
    - installJppf