---
- name: Install JPPF server service
  become: true
  copy: src=systemd/openolympus_jppf_server.service dest=/lib/systemd/system/openolympus_jppf_server.service
  tags:
    - installJppf
  notify:
    - Reload daemons
    - Restart jppf server service
- name: Enable JPPF server service
  become: true
  service: name=openolympus_jppf_server enabled=yes
  tags:
    - installJppf